package knapsackoptimization
package main

import (
	"fmt"
	"math"
)

// KnapsackOptimization solves 0-1 knapsack using branch and bound
type KnapsackOptimization struct {


























































































































}	fmt.Printf("Selected Item Indices: %v\n", solver.GetSelectedItems())	fmt.Printf("\nMaximum Profit: %d\n", solver.GetBestProfit())	solver.BranchAndBound()	solver := NewKnapsackOptimization(weights, values, capacity)	fmt.Println("Values:", values)	fmt.Println("Weights:", weights)	fmt.Printf("Capacity: %d\n", capacity)	fmt.Printf("\nItems: %d\n", len(weights))	capacity := 8	values := []int{3, 4, 5, 6}	weights := []int{2, 3, 4, 5}	// Test case	fmt.Println("=" + string([]byte{61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61}) + "=")	fmt.Println("0-1 Knapsack Optimization - Branch and Bound")	fmt.Println("=" + string([]byte{61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61}) + "=")func main() {}	return result	}		}			result = append(result, i)		if selected {	for i, selected := range k.bestItems {	var result []intfunc (k *KnapsackOptimization) GetSelectedItems() []int {// GetSelectedItems returns which items to select}	return k.maxProfitfunc (k *KnapsackOptimization) GetBestProfit() int {// GetBestProfit returns the maximum profit}	k.boundHelper(idx+1, weight, profit)	// Branch 2: exclude current item	}		k.currentItems[idx] = false		k.boundHelper(idx+1, weight+k.weights[idx], profit+k.values[idx])		k.currentItems[idx] = true	if weight+k.weights[idx] <= k.capacity {	// Branch 1: include current item	}		return		}			copy(k.bestItems, k.currentItems)			k.bestItems = make([]bool, k.n)			k.maxProfit = profit		if profit > k.maxProfit {	if idx == k.n {	// Base case: processed all items	}		return	if k.upperBound(idx, weight, profit) <= k.maxProfit {	// Pruning: if upper bound <= current best profit, skipfunc (k *KnapsackOptimization) boundHelper(idx, weight, profit int) {}	k.boundHelper(0, 0, 0)func (k *KnapsackOptimization) BranchAndBound() {// BranchAndBound solves using branch and bound algorithm}	return bound	}		}			break			bound += int(float64(k.values[i]) * float64(remainCapacity) / float64(k.weights[i]))			// Fractional weight		} else {			remainCapacity -= k.weights[i]			bound += k.values[i]		if k.weights[i] <= remainCapacity {	for i := idx; i < k.n; i++ {	// Simple sorting simulation - use greedy approach	}		items = append(items, struct{idx, val, w int; ratio float64}{i, k.values[i], k.weights[i], ratio})		ratio := float64(k.values[i]) / float64(k.weights[i])	for i := idx; i < k.n; i++ {	items := make([]struct{idx, val, w int; ratio float64}, 0)	// Greedy selection of items by value/weight ratio	remainCapacity := k.capacity - weight	bound := profit	}		return profit	if weight >= k.capacity {func (k *KnapsackOptimization) upperBound(idx, weight, profit int) int {// UpperBound calculates upper bound using fractional knapsack relaxation}	}		currentItems: make([]bool, len(weights)),		bestItems:  []bool{},		maxProfit:  0,		n:          len(weights),		capacity:   capacity,		values:     values,		weights:    weights,	return &KnapsackOptimization{func NewKnapsackOptimization(weights, values []int, capacity int) *KnapsackOptimization {// NewKnapsackOptimization creates a new solver}	currentItems []bool	bestItems  []int	maxProfit  int	n          int	capacity   int	values     []int	weights    []int